### ISSUE TITLE
Http404 exception is caught, but shouldn't

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/django-tutelary#28] opened 2016-06-28 13:35 UTC
It's more a question about [this part](https://github.com/Cadasta/django-tutelary/blob/master/tutelary/mixins.py#L82-L89).

I had a case where `get_object` raises a `Http404` exception. This is where I would think the execution should stop and the server should respond with `404` because the object we were trying to access was not found.

In the code, however, the next step is to get the permissions object by saving the form, but not committing to the database and this is where my code broke. I had a model form with only one `ChoiceField`, which can never be invalid because there's always a default value selected. Hence, the form does not raise a validation error and since the form is only saved but not committed, the database does not raise and `IntegrityError`. So we end up with an incomplete instance, in my case a `TenureRelationship` where the `project` attribute was `None`. Tutelary tried to check permissions against the instance and failed because there was no project. 

Now my question is: Why do we get the instance through a form in the first place? Forms are usually used to (a) create new model instances or (b) edit existing ones. When you create a new instance, permissions are checked against a parent model (i.e. a project when you create a party). When you edit an instance, the permissions is checked against the instance itself. But when there's no object found, there's nothing to edit and also nothing to check permissions against.

**Comment by ian-ross** [comment] 2016-07-06 18:45
This business of catching 404s and not re-raising them is definitely wrong.  I've seen some problems in some of the API tests arising from the same thing while I've been reviewing the permissions as part of fixing #303, so I'll definitely sort this out.

I can't actually remember why the object access via a form was added there.  Let me come back to it once I've modified tutelary to re-raise 404s and see if that breaks anything else.  I do remember that there was a good reason for doing it, though it always looked weird to me as well.  There isn't an equivalent in the API permissions mixin.  I hope I can get rid of it (assuming that I can work out why I put it in there in the first place - I wish I'd written a comment...).

**Comment by ian-ross** [comment] 2016-07-06 20:47
This is now fixed in version 0.1.14.  I'm integrating the new version into the platform now - there are some test coverage changes because of some other things I've changed that I need to investigate.  I got rid of the form thing, since it seems like it was just a mistake caused by flailing around trying to get something to work before...

**Closed by ian-ross** 2016-07-06 20:47 UTC
Labels: question
